name: Build AWS Infra

on:
 push:
   branches:
     - main
  #  paths:
  #    - 'terraform/main.tf'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: 
       - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform
        with:
          terraform_version: "v1.10.5"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Validate
        id: validate
        run: terraform validate

      - name: Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Apply
        id: apply
        run: terraform apply -auto-approve -input-false -no-color

      - name: Log
        run:  echo "Done"
      