name: Build AWS Infra

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - 'terraform/*'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: 
       - ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
      - uses: actions/checkout@v4
        name: Checkout Repo
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
            cache: 'pip'
      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform
        with:
          terraform_version: "v1.10.5"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
     
      - name: Install Pip Packages
        run: |
          mkdir package
          pip install --target ./package -r requirements.txt
          echo "pip packages installation done!!!"

      - name: Create Deployment Package
        run: |
          cd package
          zip -r ../function.zip .
          cd ..
          zip function.zip main.py
          cp function.zip ./terraform/function.zip
          echo "Done"

      - name: Init
        id: init
        run: terraform init
        working-directory: terraform

      - name: Validate
        id: validate
        run: terraform validate
        working-directory: terraform

      - name: Apply
        id: apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false -no-color

      - name: Log
        run:  echo "Done"
      