name: Build Zip File

on:
 push:
   branches:
     - main


jobs:
  build-and-remove:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - uses: montudor/action-zip@v1
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
            cache: 'pip'
    
        name: check out code

      - name: Install Pip Packages
        run: |
          mkdir package
          pip install --target ./package -r requirements.txt
          echo "pip packages installation done!!!"

      - name: Create Deployment Package
        run: |
          cd package
          zip -r ../function.zip .
          cd ..
          zip function.zip main.py
          echo "Done"
        
