name: Destroy AWS Infra

on:
  workflow_dispatch:
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: 
       - ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repo

      - uses: hashicorp/setup-terraform@v3
        name: Setup Terraform
        with:
          terraform_version: "v1.10.5"
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}

      - name: Init
        id: init
        run: terraform init

      - name: Destroy
        id: apply
        run: terraform apply -destroy -auto-approve -input=false -no-color

      - name: Log
        run:  echo "Done"
      